# Generated by Django 4.2.13 on 2024-06-15 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_aplicacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=10)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.oferta')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.postulante')),
            ],
        ),
    ]
